//Base Url
const kBaseURL='https://api.themoviedb.org/3';
//End Point
const kGetNowPlayingEndPoint='/movie/now_playing';
//Query Params
const  kApiKey='api_key';
const  kPages='page';
//API Token
const  kApiToken='1b285f1125bf6a30b81bee2e768e5123';
//Image Constant
const kPrefixImageLink="https://image.tmdb.org/t/p/w500";